### ISSUE TITLE
TypeError: Caught TypeError in DataLoader worker process 1.

### ISSUE THREAD

**Issue by Mirandl** [syguan96/DynaBOA#29]
Hi! There I meet a problem :

---> seed has been set
---> model and optimizer have been set
pw3d: 37
WARNING: You are using a SMPL model, with only 10 shape coefficients.
WARNING: You are using a SMPL model, with only 10 shape coefficients.
WARNING: You are using a SMPL model, with only 10 shape coefficients.
  1%|          | 200/35515 [09:03<23:55:21,  2.44s/it]Step:199: MPJPE:108.14312744140625, PAMPJPE:52.69846725463867, PVE:94.87768046557903
  1%|          | 400/35515 [17:31<28:17:38,  2.90s/it]Step:399: MPJPE:99.1795425415039, PAMPJPE:47.766239166259766, PVE:88.05403053760529
  2%|▏         | 600/35515 [25:37<13:24:34,  1.38s/it]Step:599: MPJPE:91.56452178955078, PAMPJPE:47.820899963378906, PVE:84.10537596791983
  2%|▏         | 800/35515 [30:35<18:15:24,  1.89s/it]Step:799: MPJPE:84.9598159790039, PAMPJPE:44.537147521972656, PVE:82.7759880432859
  3%|▎         | 1000/35515 [37:18<28:50:51,  3.01s/it]Step:999: MPJPE:79.5338134765625, PAMPJPE:42.920555114746094, PVE:81.89351376518607
  3%|▎         | 1200/35515 [45:19<19:36:31,  2.06s/it]Step:1199: MPJPE:76.7173080444336, PAMPJPE:42.85281753540039, PVE:82.61778503345947
  4%|▍         | 1400/35515 [50:35<19:12:54,  2.03s/it]Step:1399: MPJPE:74.18508911132812, PAMPJPE:40.78797912597656, PVE:80.56003755224603
  5%|▍         | 1600/35515 [56:14<15:07:32,  1.61s/it]Step:1599: MPJPE:73.13909912109375, PAMPJPE:41.25379943847656, PVE:77.55705753806978
  5%|▌         | 1800/35515 [1:00:38<10:39:45,  1.14s/it]Step:1799: MPJPE:72.77523803710938, PAMPJPE:42.25539016723633, PVE:76.45247981366184
  6%|▌         | 2000/35515 [1:05:01<9:35:38,  1.03s/it]Step:1999: MPJPE:73.12327575683594, PAMPJPE:42.23678970336914, PVE:76.57051902078092
  6%|▌         | 2200/35515 [1:09:42<14:54:10,  1.61s/it]Step:2199: MPJPE:72.85092163085938, PAMPJPE:41.97563171386719, PVE:75.81348557533188
  7%|▋         | 2400/35515 [1:13:13<11:36:43,  1.26s/it]Step:2399: MPJPE:71.45988464355469, PAMPJPE:41.051570892333984, PVE:74.75854421810557
  7%|▋         | 2600/35515 [1:17:23<10:32:56,  1.15s/it]Step:2599: MPJPE:71.4017562866211, PAMPJPE:41.07121276855469, PVE:76.12829965467637
  8%|▊         | 2800/35515 [1:21:17<6:36:03,  1.38it/s]Step:2799: MPJPE:70.69111633300781, PAMPJPE:41.131832122802734, PVE:76.1530753770577
  8%|▊         | 3000/35515 [1:24:56<8:37:23,  1.05it/s]Step:2999: MPJPE:69.84212493896484, PAMPJPE:40.65814971923828, PVE:75.713991060853
  9%|▉         | 3200/35515 [1:29:11<9:58:27,  1.11s/it]Step:3199: MPJPE:68.54174041748047, PAMPJPE:39.8968620300293, PVE:74.9515091557987
  9%|▉         | 3257/35515 [1:30:18<14:54:30,  1.66s/it]
Traceback (most recent call last):
  File "/home/DynaBOA/dynaboa_benchmark.py", line 292, in <module>
    adaptor.excute()
  File "/home/DynaBOA/dynaboa_benchmark.py", line 89, in excute
    for step, batch in tqdm(enumerate(self.dataloader), total=len(self.dataloader)):
  File "/home/miniconda3/envs/DynaBOA-env/lib/python3.6/site-packages/tqdm/std.py", line 1166, in __iter__
    for obj in iterable:
  File "/home/miniconda3/envs/DynaBOA-env/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/miniconda3/envs/DynaBOA-env/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home/miniconda3/envs/DynaBOA-env/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/miniconda3/envs/DynaBOA-env/lib/python3.6/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
**TypeError: Caught TypeError in DataLoader worker process 1.**
Original Traceback (most recent call last):
  File "/home/miniconda3/envs/DynaBOA-env/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/miniconda3/envs/DynaBOA-env/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/miniconda3/envs/DynaBOA-env/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/DynaBOA/boa_dataset/pw3d.py", line 101, in __getitem__
    image = self.read_image(imgname, index)
  File "/home/DynaBOA/boa_dataset/pw3d.py", line 146, in read_image
    img = cv2.imread(imgname)[:, :, ::-1].copy().astype(np.float32)
**TypeError: 'NoneType' object is not subscriptable**

Process finished with exit code 1
-------------
The errors all drop quickly but ...  have you ever met this problem?  I tried but failed to find where this error comes from.
It seems that some data are needed but missed. Maybe the labeled data? 

I'm sure I followed all your descriptions and the human3.6m and 3dpw data has placed properly and input totally. 
Could you please give me a little guidance?   I'll be very appreciated it. Thank you!

**Comment by syguan96** [comment]
it seems that image doesnt exists at imagepath. Set numwoker=0, and then check whether imagepath is correct by using ‘try except ‘
